baseURL = "https://teatro-vivo.onrender.com/"
languageCode = "es-co"
DefaultContentLanguage = "es"
title = "Teatro Vivo Colombia"
theme = "meghna"

# Menu
[menu]
    [[menu.nav]]
    name = "Escuela de actuaci칩n"
    URL = "/escuela-actuacion"
    weight = 2

    [[menu.nav]]
    name = "Casa Teatro de Bogot치"
    URL = "/casa-teatro"
    weight = 3

    [[menu.nav]]
    name = "Escuela de Comunicacion Efectiva"
    URL = "/escuela-comunicacion"
    weight = 4

    [[menu.nav]]
    name = "Nuestras Obras"
    URL = "#services"
    weight = 5

    [[menu.nav]]
    name = "Contactenos"
    URL = "#contact-us"
    weight = 6

# Site params
[params]
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Compa침ia Teatro Vivo de Colombia"
author = "Oficina Creativa Web CTVC"
# Google Analitycs
#googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/sox.gif"
    heading = "Vive Un Nuevo Teatro"
    content= "Donde el espectador es protagonista!!"
    btn = true
    btnText="Comprar Entradas"
    btnURL="/comprar-entradas"

    # call to action
    [params.cta]
        enable = true
        title = "Quieres ser actor??!!"
        content = "Inscribete a nuestro curso regular e actuaci칩n."
        btnURL = "/escuela-actuacion"
        btnText = "Inscribete"

    [params.counter]
    enable = false
    bgImage = "images/backgrounds/bg-1.jpg"

    # footer
    [params.footer]
        copyright = "Oficina Creativa Web CTVC"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "https://www.facebook.com/paginateatrovivocolombia/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/teatro_vivo"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "https://www.youtube.com/user/Mauriciosuarezs"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "https://www.instagram.com/teatro_vivo/"
